### ISSUE TITLE
Bugfix: Fikse navigasjonsknapper/meny/tab-greier

### ISSUE THREAD

**Issue by sarahse** [varianter/joy#117]

**Comment by sarahse** [comment]
![Image](https://github.com/varianter/joy/assets/6595982/85e75a27-9daf-4e7c-b816-a3d2534dcf88)

**Comment by teatimes** [comment]
Gjelder også admin. 

Fonttype som brukes nå er egentlig reservert titler. Og det bør være mer fokus på teskten enn ikonet, siden ikonet er et hjelpemiddel.

**Comment by sarahse** [comment]
Må se på denne igjen etter brukertestene

**Comment by sarahse** [comment]
Legg til overskrift på kategori-navnet og tilbake-knapp også

**Comment by sarahse** [comment]
Bytter til enklere meny isteden.

![Image](https://github.com/varianter/joy/assets/6595982/46fa35f3-5af4-487e-9a2f-6b4ac6491918)
![Image](https://github.com/varianter/joy/assets/6595982/0300cca1-7418-4d11-ae81-4ec7d9c6768d)

**Comment by sarahse** [comment]
> Mikael
  [1 minute ago](https://variantas.slack.com/archives/C053KD4LEEQ/p1684737319370619?thread_ts=1684237736.310899&cid=C053KD4LEEQ)
Stemmer for å ha en slik enklere meny, men trenger ikke noe Se: prefiks. Ang mobilvisning tenker jeg at dette er så pass liten og enkel meny som ikke tar så mye plass så det er et enkelt og greit førstesteg å bare la den wrappe til flere linjer. Så kan det ev. utvides til dropdown-meny senere
