### ISSUE TITLE
Legg til bedre bilder på de ulike ressursene som har bedre oppløsning og legg til tags

### ISSUE THREAD

**Issue by mathildehaugum** [varianter/joy#138]
Flere av bildene vi har lagt til nå har dårlig oppløsning og kuttes merkelig, og dette har mye å si for hvordan nettsiden ser ut. Derfor bør det legges til bilder (evt. bruke AI for å generere nye) som ser bedre ut før NDC!

**Comment by sarahse** [comment]
Vi må også legge til tags

**Comment by teatimes** [comment]
Jeg har lagt til til noen tags basert på tags i orgianalartikkel o.l. på innholdet som var lagt inn før 17. mai

**Comment by sarahse** [comment]
Synes det ser bra ut nå! Vi får passe på å legge til gode bilder når vi legger til ressurser nå fremover 😊
