### ISSUE TITLE
Funksjonalitet - lik størrelse på seksjoner på bloggposter som er featured/ikke featured

### ISSUE THREAD

**Issue by sarahse** [varianter/joy#30]
Fra dette

![Image](https://user-images.githubusercontent.com/6595982/227159834-16690537-151a-438d-83cd-9bfff872cc81.png)

til dette

![Image](https://user-images.githubusercontent.com/6595982/227159903-f9ab7d9c-b5c9-4f46-b55f-2277affbbfd9.png)

**Comment by sarahse** [comment]
Se på padding, margin og screen-size breakpoints

**Comment by mamarku** [comment]
Dere står fritt til å justere screen size, disse kan justeres i `tailwind.config.js`.

Padding/margin justeres med breakpoints i `Layout.tsx`. Ideelt sett så skal kun headeren flyte sammen med bredden på skjermen, men alt innholdet skal være sentrert og "uprega".
