### ISSUE TITLE
Bugfix: max 3 fremhevede cards på hver kategori, justere padding på framhevede cards

### ISSUE THREAD

**Issue by sarahse** [varianter/joy#73]
- Juster padding på cards
- Endre slik at det max er 3 fremhevede cards per kategori
- Vis resterende ressurser i "alle bloggposter"/"resterende bloggposter"

![Image](https://user-images.githubusercontent.com/19650599/229064156-427b5c98-7246-44fe-af55-e79a60fc932b.png)

**Comment by teatimes** [comment]
Hva slags justeringer er det snakk om her?

**Comment by sarahse** [comment]
Det skal være mer padding, tror jeg. Ref skisser: https://www.figma.com/file/ZzG9yT7hVU17lgfRJPdoMp/L%C3%A6reglede?type=design&node-id=5-664&t=K4KqqhHuVlpBiJIr-0
