### ISSUE TITLE
Bugfix: Mobilvisning

### ISSUE THREAD

**Issue by sarahse** [varianter/joy#86]
For lite padding på sidene på footeren, for mye margin i topp/bunn mellom elementer, for mye padding på cards, rart i toppen av siden.

<img src="https://user-images.githubusercontent.com/6595982/235867292-f1f5b756-deaa-4347-bb6e-ea283cfb4bdb.png" width="350"><img src="https://user-images.githubusercontent.com/6595982/235867293-4ee76ade-dff3-4434-a7b9-1332dd5ca6b5.png" width="350">

**Comment by sarahse** [comment]
Mikaels kommentarer:
- Ikke noe space på footer, men mye space i toppen = fikse spacing i mobilvisning
- Overflow text på ei linje, blir det bare de første par ordene på tittelene (mindre størrelse på overskrift så vi får til mer av tittel)
- Hele kortet bør være klikkbart, merkelig på mobil når det ser ut som et kort
- Admin må også tilpasses mobil visning (nice-to-have)
- Fikse typografisk rot, vanskelig å følge visuelt hierarki
- Tittel er for stor

**Comment by mathildehaugum** [comment]
OBS! Det ser ut til å være noe overlapp med issue 90, så her må vi passe på at det ikke blir dobbeltarbeid

**Comment by mathildehaugum** [comment]
OBS: det ser ut til å være noe overlapp med issue 90, så vi må passe på at det ikke blir dobbeltarbeid 😅

**Comment by teatimes** [comment]
Blir fikset i #111
